-- vim.opt.backupdir="~/.vim/backup,/tmp"
-- vim.opt.directory="~/.vim/swap,/tmp"
-- vim.opt.undodir="~/.vim/undo,/tmp"
vim.opt.undofile=true
vim.opt.relativenumber=true
vim.opt.number=true
vim.opt.colorcolumn="120"
vim.opt.ruler=true
vim.opt.wrap=false
vim.opt.autoindent=true
vim.opt.hlsearch=true
vim.opt.incsearch=true
vim.opt.tabstop=2
vim.opt.shiftwidth=2
vim.opt.softtabstop=2
vim.opt.backspace="indent,eol,start"
vim.opt.expandtab=true
vim.opt.spell=true
vim.opt.spelllang="en_us"
vim.opt.timeoutlen=500
vim.opt.updatetime=1000
vim.opt.completeopt="menuone,noinsert,noselect,preview"
vim.opt.mouse=""
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
