#!/usr/bin/env bash

DEV_CONTEXT_PATH=$(pwd)
DEV_CONTAINER_NAME=$(md5 -qs $DEV_CONTEXT_PATH)
CONTAINER_NAME=a31b1314dcf6

if [ ! "$(docker ps -q -f name=$DEV_CONTAINER_NAME)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=$DEV_CONTAINER_NAME)" ]; then
        # cleanup
        docker rm $DEV_CONTAINER_NAME
    fi
    # run your container
    touch ~/.zsh_history
    docker run -itd \
      --volume $DEV_CONTEXT_PATH:/workspace/$DEV_CONTEXT_PATH \
      -w=/workspace/$DEV_CONTEXT_PATH \
      --volume ~/.ssh:/root/.ssh \
      --volume /tmp:/tmp \
      --volume ~/.zsh_history:/root/.zsh_history \
      --env SSH_AUTH_SOCK=/ssh-agent \
      --name $DEV_CONTAINER_NAME \
      $CONTAINER_NAME tmux
fi

docker attach $(docker ps -q -f name=$DEV_CONTAINER_NAME)
