#!/usr/bin/env bash

DEV_CONTEXT_PATH=$(pwd)
DEV_CONTAINER_NAME=$(md5 -qs $DEV_CONTEXT_PATH)

if [ ! "$(docker ps -q -f name=$DEV_CONTAINER_NAME)" ]; then
    if [ "$(docker ps -aq -f status=exited -f name=$DEV_CONTAINER_NAME)" ]; then
        # cleanup
        docker rm $DEV_CONTAINER_NAME
    fi
    # run your container
    docker run -itd --name $DEV_CONTAINER_NAME 8bd73f5292c1 tmux
fi

docker attach -name $DEV_CONTAINER_NAME
